### ISSUE TITLE
Unable to download File

### ISSUE THREAD

**Issue by juliourena** [zerosum0x0/koadic#101]
Hi, I'm trying to download a 20mb file using /implant/util/download_file and I'm getting this error

```
[v] Server: <Server(Thread-249, started daemon 140487007573760)> Sesson <core.session.Session object at 0x7fc5af18dd68>
[*] Zombie 0: Job 0 (implant/util/download_file) created.
[v] session::get_created_job - fetched job.key = AAAAAAAAAAAAAAAAAAAAAAAAA
[v] handler::reply() - sending status 201 with 32 bytes to ('1.1.1.1', 1987)
[v] handler::handle() - Incoming HTTP from ('1.1.1.1', 1988)
[v] handler::find_session() - found session.key = BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
[v] self.params:  {'CCCCCCCCCCCCCCCCCCCCCCCCCCC': ['BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'], 'DDDDDDDDDDDDDDDDDDDDDDDDD': ['stage']}
[v] handler::handle() - Incoming HTTP from ('1.1.1.1', 1992)
[v] handler::find_session() - found session.key = BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
[v] self.params:  {'CCCCCCCCCCCCCCCCCCCCCCCCCCC': ['BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'], 'DDDDDDDDDDDDDDDDDDDDDDDDD': ['AAAAAAAAAAAAAAAAAAAAAAAAA']}
[v] handler::parse_params() - fetched job_key = AAAAAAAAAAAAAAAAAAAAAAAAA
[v] handler::reply() - sending status 200 with 7575 bytes to ('1.1.1.1', 1992)
[v] handler::handle() - Incoming HTTP from ('1.1.1.1', 1989)
[v] handler::handle() - Incoming HTTP from ('1.1.1.1', 1995)
[v] handler::find_session() - found session.key = BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
[v] self.params:  {'CCCCCCCCCCCCCCCCCCCCCCCCCCC': ['BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'], 'DDDDDDDDDDDDDDDDDDDDDDDDD': ['AAAAAAAAAAAAAAAAAAAAAAAAA']}
[v] handler::parse_params() - fetched job_key = AAAAAAAAAAAAAAAAAAAAAAAAA
(koadic: imp/uti/download_file)# ----------------------------------------
Exception happened during processing of request from ('1.1.1.1', 1995)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/opt/koadic/core/handler.py", line 90, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/opt/koadic/core/handler.py", line 216, in do_POST
    return self.handle_report()
  File "/opt/koadic/core/handler.py", line 324, in handle_report
    self.job.report(self, data)
  File "modules/implant/util/download_file.py", line 50, in report
    data = self.decode_downloaded_data(data, handler.get_header("encoder", "1252"))
  File "/opt/koadic/core/job.py", line 186, in decode_downloaded_data
    return b"".join(b_list)
MemoryError
----------------------------------------
[v] handler::handle() - Incoming HTTP from ('1.1.1.1', 1996)
[v] handler::find_session() - found session.key = BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
[v] self.params:  {'CCCCCCCCCCCCCCCCCCCCCCCCCCC': ['BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'], 'DDDDDDDDDDDDDDDDDDDDDDDDD': ['AAAAAAAAAAAAAAAAAAAAAAAAA']}
[v] handler::parse_params() - fetched job_key = AAAAAAAAAAAAAAAAAAAAAAAAA
[-] Zombie 0: Job 0 (implant/util/download_file) failed!
[-] Error (80072f78): The server returned an invalid or unrecognized response
[v] handler::reply() - sending status 200 with 0 bytes to ('1.1.1.1', 1996)
```

It's there a file limit?? Any recommendations?

**Comment by TheNaterz** [comment]
You're somehow running out of memory. Are you sure it's a 20mb file and not 20gb? I have a fix for downloading large files in implant/gather/hashdump_dc's save_file method, I haven't ported it to this implant yet for some reason. It takes the raw data, cuts it up into chunks, saves each chunk to a file, and then concatenates all the file chunks into one. You can try editing the module to toss in the fix and see if that works out for you. I'll try pushing something out this week.

**Comment by TheNaterz** [comment]
Pushed out a fix. Go ahead and pull, see if it works out for you. New option CHUNKSIZE will help avoid some MemoryErrors in the future. Will try working on a solution to control the chunk size of data coming back in the future.
