### ISSUE TITLE
koadic fails to start without a default gateway

### ISSUE THREAD

**Issue by srpape** [zerosum0x0/koadic#109]
If the system has no default gateway set, koadic fails to launch:

```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.0.0      0.0.0.0         255.255.0.0     U     100    0        0 eth0

# ./koadic 
Traceback (most recent call last):
  File "./koadic", line 53, in <module>
    shell = core.shell.Shell(banner, __version__)
  File "/root/acs-kali-additions/src/koadic/core/shell.py", line 18, in __init__
    self.plugins = core.loader.load_plugins("modules", True, self)
  File "/root/acs-kali-additions/src/koadic/core/loader.py", line 39, in load_plugins
    plugins[pname] = obj(shell)
  File "modules/stager/js/bitsadmin.py", line 12, in __init__
    super(BitsadminStager, self).__init__(shell) # stupid hack inc!
  File "/root/acs-kali-additions/src/koadic/core/stager.py", line 18, in __init__
    s.connect(('8.8.8.8', 80))
OSError: [Errno 101] Network is unreachable
```

Here's the relevant code in stager.py:
```python
         s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
         hostname = '0.0.0.0'
         try:
             s.connect(('8.8.8.8', 80))
             hostname = s.getsockname()[0]
         finally:
             s.close()
```

**Comment by srpape** [comment]
I'm not 100% sure on the intended behavior, but it looks like the try/finally should be silencing exceptions and leaving hostname at 0.0.0.0 on failure.

The following change fixes the problem for me:
```python
         s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
         hostname = '0.0.0.0'
         try:
             s.connect(('8.8.8.8', 80))
             hostname = s.getsockname()[0]
         except:
             pass
         finally:
             s.close()
```

**Comment by TheNaterz** [comment]
Sure, seems sane. I'll push this out real quick, thanks for the heads up.
