### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by eaglefn** [zerosum0x0/koadic#147]
Server: Koadic latest on Kali2021  and Ubuntu
Client:  Windows 10

I have the same problems with other stager (mshta, regsvr32)
I tried the same in the local network with the same error message. AniVirus is off.

[+] Zombie 1: Staging new connection (xxx.57.83) on Stager 0
[+] Zombie 1: WIN10PC\John @ WIN10PC -- Windows 10 Pro
(koadic: sta/js/bitsadmin)# ----------------------------------------
Exception happened during processing of request from ('176.xxx.57.xx', 50553)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/opt/koadic/core/handler.py", line 89, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/koadic/core/handler.py", line 209, in do_GET
    if self.parse_params():
  File "/opt/koadic/core/handler.py", line 139, in parse_params
    self.get_params = self.parse_qs(splitted)
  File "/opt/koadic/core/handler.py", line 129, in parse_qs
    pv = p.split('=', 1)[1]
IndexError: list index out of range
----------------------------------------
[!] Zombie 1: Timed out.

**Comment by TheNaterz** [comment]
Try pulling and running again.

**Comment by eaglefn** [comment]
It works! Thanks!
