### ISSUE TITLE
Exception happened during processing of request from ('IP ADDRESS')

### ISSUE THREAD

**Issue by UnknownBean** [zerosum0x0/koadic#64]
i'm running into an error when i try and connect to any stager using any computer. it all sets up and runs but when an inbound connection happens it crashes. i have installed all dependencies including rjsmin and jsmin. side note, a very old version of koadic from around a year ago work just fine. 

Error Message: 

(koadic: sta/js/mshta)$ ----------------------------------------
Exception happened during processing of request from ('192.168.86.144', 51305)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/anon/github/koadic/core/handler.py", line 90, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/home/anon/github/koadic/core/handler.py", line 149, in do_GET
    return self.handle_new_session()
  File "/home/anon/github/koadic/core/handler.py", line 197, in handle_new_session
    data = self.post_process_script(self.options.get("_STAGE_"))
  File "/home/anon/github/koadic/core/handler.py", line 311, in post_process_script
    from rjsmin import jsmin
ModuleNotFoundError: No module named 'rjsmin'
----------------------------------------
[!] Zombie 0: Timed out.

**Comment by TheNaterz** [comment]
"ModuleNotFoundError: No module named 'rjsmin'"

pip install rsjmin

**Comment by UnknownBean** [comment]
I have already tried running that, its installed already.

**Comment by TheNaterz** [comment]
Are you sure you have rjsmin installed for python3? "ModuleNotFoundError: No module named 'rjsmin'" is a pretty clear error.

**Comment by UnknownBean** [comment]
That's what I thought but it's already installed.

**Comment by TheNaterz** [comment]
Try a virtualenv, that will solve it for sure.

**Comment by UnknownBean** [comment]
Ok, I'll give it a shot and report back.

**Comment by UnknownBean** [comment]
Using virtualenv worked, I got it to run perfectly. Thank you for your assistance on this weird issue I was having.
