### ISSUE TITLE
No module named 'rjsmin'

### ISSUE THREAD

**Issue by pl4f0rd** [zerosum0x0/koadic#65]
The tool outputs the below errors. The module is installed as per the requirements.txt
Any ideas as to what's going on?

Exception happened during processing of request from ('192.168.0.19', 50713)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/root/koadic/core/handler.py", line 90, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/root/koadic/core/handler.py", line 149, in do_GET
    return self.handle_new_session()
  File "/root/koadic/core/handler.py", line 197, in handle_new_session
    data = self.post_process_script(self.options.get("_STAGE_"))
  File "/root/koadic/core/handler.py", line 311, in post_process_script
    from rjsmin import jsmin
ModuleNotFoundError: No module named 'rjsmin'

Many Thanks

**Comment by pl4f0rd** [comment]
I just want to add i'm working from a virtual environment, up to date Kali and rjsmin is installed. 
pip install rjsmin
Requirement already satisfied: rjsmin in /usr/local/lib/python2.7/dist-packages

**Comment by TheNaterz** [comment]
I know exactly what's going on. I changed Koadic's shebang to use python3 in a recent commit. Simply invoke Koadic with python2, or install rjsmin for python3 using either `python3 -m pip install rjsmin` or `pip3 install rjsmin`.

**Comment by TheNaterz** [comment]
Ultimately, a python environment issue.
